/* ------------------------------------------------------------------ */
/* CONTENT DATA                                                        */
/* ------------------------------------------------------------------ */

const ACCESSFM = [
  { id: "a1", letter: "A", word: "Aesthetics", icon: "Palette",
    desc: "How the product looks, feels and appeals to the user \u2014 shape, colour, pattern and finish.",
    simple: "How does it look? Do people like the colours, shape and style?",
    example: "A smoothie maker with soft curves and a matte finish feels friendly on a kitchen worktop.",
    prompt: "Describe the look and feel of your product. What shapes, colours, textures or finishes will make it appealing?",
    analyzePrompt: "How does this product look and feel? What do you think makes it appealing \u2014 or not?",
    wordbank: ["bright colours", "smooth finish", "modern style", "bold pattern", "simple shape", "eye-catching", "matches other products"],
    starters: ["I want my product to look...", "I will use these colours because...", "My design will stand out because..."],
    analyzeStarters: ["This product looks...", "I think people would like this because...", "The colours and shape make me think..."],
    scenario: "A furniture company redesigns their bookshelf with smooth curves, a choice of three trending colours, and a glossy finish that matches modern living rooms." },
  { id: "c1", letter: "C", word: "Cost", icon: "Coins",
    desc: "What it costs to make and to buy \u2014 materials, manufacturing and profit margin.",
    simple: "How much money does it take to make, and how much will people pay for it?",
    example: "A flat-pack chair uses cheap board and simple joints to keep the price down.",
    prompt: "Estimate what your product might cost to make. Where could you save money without ruining the quality?",
    analyzePrompt: "How much do you think this product costs to make and to buy? Does it seem good value?",
    wordbank: ["cheap to make", "good value", "affordable", "low-cost materials", "keeps the price down", "worth the money"],
    starters: ["My product could cost around...", "I can keep the cost low by...", "This part might be expensive because..."],
    analyzeStarters: ["I think this costs around... because...", "This looks like good value because...", "This might be expensive to make because..."],
    scenario: "A phone case brand switches to a cheaper plastic and simplifies the mould design, cutting the retail price by \u00a33." },
  { id: "c2", letter: "C", word: "Customer", icon: "Users",
    desc: "Who the product is designed for \u2014 their age, needs, lifestyle and budget.",
    simple: "Who will use this product? What do they need?",
    example: "A children's toothbrush has a chunky handle sized for small hands.",
    prompt: "Who exactly is this product for? What do they need from it that other products don't give them?",
    analyzePrompt: "Who do you think this product was designed for? How can you tell?",
    wordbank: ["teenagers", "young children", "busy parents", "older people", "students", "easy to hold", "comfortable to use"],
    starters: ["My product is designed for...", "This person needs...", "It will be easy for them to use because..."],
    analyzeStarters: ["I think this was designed for... because...", "This suggests it's aimed at...", "The clues that show me this are..."],
    scenario: "A backpack is designed with reflective strips, a padded laptop sleeve, and straps sized for a 12-year-old's shoulders." },
  { id: "e1", letter: "E", word: "Environment", icon: "Leaf",
    desc: "The impact on the planet \u2014 materials, energy use, waste and recyclability.",
    simple: "Does the product harm the planet, or help it?",
    example: "A bamboo phone case biodegrades instead of sitting in landfill for centuries.",
    prompt: "What happens to your product at the end of its life? Could it use recycled or renewable materials?",
    analyzePrompt: "What impact might this product have on the environment? Could it be more sustainable?",
    wordbank: ["recyclable", "biodegradable", "reduces waste", "made from recycled material", "long-lasting", "energy-saving"],
    starters: ["My product is good for the environment because...", "At the end of its life, my product will...", "I could reduce waste by..."],
    analyzeStarters: ["This product could affect the environment by...", "It could be more sustainable if...", "One eco-friendly feature is..."],
    scenario: "A shampoo brand switches from a plastic bottle to a compostable cardboard tube." },
  { id: "s1", letter: "S", word: "Size", icon: "Ruler",
    desc: "The dimensions and proportions \u2014 does it fit the space, the task and the user?",
    simple: "Is it the right size for the job and the person using it?",
    example: "A fold-flat drying rack is sized to fit inside a standard airing cupboard.",
    prompt: "What size does your product need to be? Think about the space and the people using it.",
    analyzePrompt: "Is the size right for its purpose and user? Why or why not?",
    wordbank: ["compact", "lightweight", "fits easily", "small enough to carry", "large enough for", "the right height"],
    starters: ["My product needs to be...", "It has to fit...", "The size is important because..."],
    analyzeStarters: ["The size seems right because...", "This size works well because...", "It might be a problem if..."],
    scenario: "A travel kettle is designed to be small enough to fit in a suitcase, holding just enough water for two cups." },
  { id: "s2", letter: "S", word: "Safety", icon: "ShieldCheck",
    desc: "How safe the product is to make, use and dispose of.",
    simple: "Could the product hurt someone? How can the design stop that?",
    example: "A kettle's handle stays cool to the touch to prevent burns.",
    prompt: "What hazards could your product create? How will your design reduce or remove them?",
    analyzePrompt: "Are there any safety features you can spot, or any hazards?",
    wordbank: ["rounded edges", "no sharp parts", "stays cool to touch", "stable base", "non-toxic materials", "clear warning label"],
    starters: ["A possible danger is...", "To keep the user safe, I will...", "I need to think about..."],
    analyzeStarters: ["A safety feature I can see is...", "A possible hazard is...", "This keeps the user safe by..."],
    scenario: "A hairdryer is fitted with a heat-resistant handle and an automatic cut-off switch if it overheats." },
  { id: "f1", letter: "F", word: "Function", icon: "Settings",
    desc: "What the product actually does, and how well it does it.",
    simple: "What job does the product need to do?",
    example: "A multi-tool works as a knife, screwdriver and bottle opener in one.",
    prompt: "What is the main job your product has to do? What secondary jobs might it also do?",
    analyzePrompt: "How well do you think this product does its job? Does it do more than one job?",
    wordbank: ["works quickly", "easy to use", "reliable", "multi-purpose", "does the job well", "simple to operate"],
    starters: ["The main job of my product is to...", "It also needs to...", "It will work by..."],
    analyzeStarters: ["This product's main job is to...", "I think it works well because...", "It also seems to..."],
    scenario: "A watch is designed to tell the time, track steps, and show text message notifications." },
  { id: "m1", letter: "M", word: "Materials", icon: "Layers",
    desc: "What it's made from, and why those materials suit the job.",
    simple: "What is it made from, and why is that a good choice?",
    example: "A saucepan uses stainless steel for the body and heat-resistant plastic for the handle.",
    prompt: "What materials will you use, and why are they suitable \u2014 strength, cost, appearance, weight?",
    analyzePrompt: "What materials is it made from? Why do you think the designer chose them?",
    wordbank: ["strong", "waterproof", "lightweight", "recycled plastic", "natural wood", "stainless steel", "flexible"],
    starters: ["I will use... because...", "This material is good for my product because...", "One material I am considering is..."],
    analyzeStarters: ["I think this is made from... because...", "This material was probably chosen because...", "It looks like it is made of..."],
    scenario: "A saucepan is made with a copper base for even heating and a heat-resistant plastic handle." },
];

const SCAMPER = [
  { id: "s1", letter: "S", word: "Substitute", icon: "Repeat",
    desc: "Swap a material, part, process or ingredient for something else.",
    simple: "Can you swap one part or material for something different?",
    example: "Swapping a glass bottle for a lightweight aluminium can.",
    prompt: "What could you swap out in your design \u2014 a material, a part, a process?",
    analyzePrompt: "Could any part or material of this product be substituted for something better?",
    wordbank: ["swap the material", "use a different part", "replace with something lighter", "try a new process", "use an alternative"],
    starters: ["I could substitute... with...", "Instead of using..., I could use...", "One thing I could swap is..."],
    analyzeStarters: ["A better material might be...", "Swapping... for... could improve it because...", "I would substitute... with..."],
    scenario: "A shoe designer replaces the leather upper with a recycled mesh fabric to cut cost and weight." },
  { id: "c1", letter: "C", word: "Combine", icon: "GitMerge",
    desc: "Merge two ideas, products or functions into one.",
    simple: "Can you join two ideas or jobs together to make one new idea?",
    example: "A printer that also scans and photocopies.",
    prompt: "Could you combine your product with another idea or function?",
    analyzePrompt: "Could this product be combined with another product or feature to add value?",
    wordbank: ["combine two functions", "merge with another product", "join together", "two-in-one design", "add an extra feature"],
    starters: ["I could combine my idea with...", "What if it also did...", "Joining these two ideas would..."],
    analyzeStarters: ["This could be combined with...", "Adding... would improve it because...", "It might work well alongside..."],
    scenario: "A designer adds a built-in bottle opener to the end of a camping multi-tool." },
  { id: "a1", letter: "A", word: "Adapt", icon: "RefreshCw",
    desc: "Change part of the design to suit a new purpose or improve it.",
    simple: "Can you copy or change an idea from somewhere else?",
    example: "Velcro was adapted from the way burrs cling to fur.",
    prompt: "What could you adapt from another product, or from nature, to improve your design?",
    analyzePrompt: "Has anything about this product been adapted from another product or from nature? What else could be adapted?",
    wordbank: ["copy from nature", "borrow an idea from", "change the shape of", "adjust to fit", "inspired by"],
    starters: ["I could adapt this idea from...", "This reminds me of..., so I could...", "I might change this part to..."],
    analyzeStarters: ["This feature looks adapted from...", "I think the designer was inspired by...", "Something else that could be adapted is..."],
    scenario: "A running shoe sole is redesigned to copy the grip pattern found on a mountain goat's hoof." },
  { id: "m1", letter: "M", word: "Modify", icon: "SlidersHorizontal",
    desc: "Make a feature bigger, smaller, or change it in some way.",
    simple: "Can you make a part bigger, smaller or different?",
    example: "A travel-size shampoo bottle shrinks the packaging for convenience.",
    prompt: "What could you make bigger, smaller, louder, stronger or lighter?",
    analyzePrompt: "What could be modified about this product to improve it?",
    wordbank: ["make it smaller", "make it bigger", "make it stronger", "make it lighter", "change the colour", "add more detail"],
    starters: ["I could make... bigger by...", "Changing the... would...", "One modification I could make is..."],
    analyzeStarters: ["I would modify... by making it...", "Changing... would improve it because...", "One thing I'd make bigger or smaller is..."],
    scenario: "A backpack's shoulder straps are made wider and more padded to reduce pressure on the wearer." },
  { id: "p1", letter: "P", word: "Put to another use", icon: "Recycle",
    desc: "Find a new use for the product, or for its parts.",
    simple: "Could this be used for a different job?",
    example: "Bubble wrap was originally designed and sold as wallpaper.",
    prompt: "Could your product \u2014 or parts of it \u2014 be used for something else entirely?",
    analyzePrompt: "Could this product, or part of it, be used differently?",
    wordbank: ["reuse for", "repurpose as", "could also work as", "a new use for this could be"],
    starters: ["This part could also be used for...", "Instead of throwing it away, it could become...", "A new use for this might be..."],
    analyzeStarters: ["This could also be used for...", "Instead of its usual job, it could...", "A new use for this might be..."],
    scenario: "An old shipping container is turned into a small coffee shop instead of being scrapped." },
  { id: "e1", letter: "E", word: "Eliminate", icon: "Eraser",
    desc: "Remove a part, feature or step to simplify the design.",
    simple: "Can you take a part away to make it simpler, cheaper or safer?",
    example: "Cordless tools eliminate the need for a trailing cable.",
    prompt: "What could you remove from your design to make it simpler, cheaper or safer?",
    analyzePrompt: "Is there anything unnecessary about this product that could be removed to improve it?",
    wordbank: ["remove the", "simplify by taking away", "no longer needs", "cut out the", "make it simpler"],
    starters: ["I could remove... because...", "This part isn't needed because...", "Taking away... would make it..."],
    analyzeStarters: ["I think... could be removed because...", "This part doesn't seem necessary because...", "Removing... would make it..."],
    scenario: "A juice carton removes the plastic cap entirely, replacing it with a fold-and-tear spout." },
  { id: "r1", letter: "R", word: "Reverse", icon: "ArrowLeftRight",
    desc: "Flip the order, layout or direction of something.",
    simple: "Can you turn it around, or do it in a different order?",
    example: "A reversible jacket can be worn inside-out for a second look.",
    prompt: "What could you reverse or rearrange \u2014 the order of steps, the layout, the direction?",
    analyzePrompt: "Could anything about this product be reversed or rearranged to work better?",
    wordbank: ["reverse the order", "flip it around", "turn inside out", "swap the direction", "do it backwards"],
    starters: ["I could reverse... by...", "What if I did this in the opposite order?", "Turning it around would..."],
    analyzeStarters: ["Reversing... could improve it by...", "Rearranging... would...", "What if the order or direction was flipped?"],
    scenario: "A jacket is designed so it can be worn inside out as a completely different colour and pattern." },
];

const FRAMEWORKS = {
  accessfm: { label: "ACCESSFM", full: "A checklist for designing new products and evaluating existing ones", items: ACCESSFM, tint: "#2F8FA6" },
  scamper: { label: "SCAMPER", full: "A toolkit for generating new ideas and improving existing designs", items: SCAMPER, tint: "#E2601B" },
};
